services:
  remnawavedb:
    image: postgres:17.6
    container_name: remnawavedb
    hostname: remnawavedb
    restart: always
    command: postgres -c 'max_connections=5000'
    shm_size: 8gb
    env_file:
      - stack.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=UTC
    ports:
      - '127.0.0.1:5437:5432'
    networks:
      - remnawave_internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 3s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  remnawave_internal:
    external: true
